spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  connection-timeout: 60000
  session.timeout: 60000
  port: 8084
  servlet:
    context-path: /api

services-security:
  username: one-dev
  password: 008a8005-c66a-4888-b115-32d95572c213
  role: API

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: group-id
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

