spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  connection-timeout: 60000
  session.timeout: 60000
  port: 8086
  servlet:
    context-path: /api

services-security:
  username: one-dev
  password: 008a8005-c66a-4888-b115-32d95572c213
  role: API

#  data:
#    mongodb:
#      authentication-database: admin
#      host: localhost
#      port: 27017
#      database: images
#      username: user
#      password: password

  spring:
    kafka:
      service-air:
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.agencia.car.model"
      service-reservas:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: group-id
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

