spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

  spring:
    data:
      mongodb:
        uri: ${SPRING_DATA_MONGODB_URI}

server:
  connection-timeout: 60000
  session.timeout: 60000
  port: 8086
  servlet:
    context-path: /api

services-security:
  username: one-dev
  password: 008a8005-c66a-4888-b115-32d95572c213
  role: API

  spring:
    kafka:
      consumer:
        group-id: consumer-group
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"





